{% set name = "lipo" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 981706fb20c21c617341996e2e57dec4a369d57aab5bd716431195a6e9b15ebe

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=1.0.5
  run:
    - dlib >=19.19.0,<20.0.0
    - python >=3.6
    - scikit-learn >=0.22.1
    - tqdm >=4.46.0,<5.0.0

test:
  requires:
    - pip
  imports:
    - lipo
  commands:
    - python -m pip check

about:
  home: https://github.com/jdb78/lipo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Global, derivative-free optimization"
  description: |
    "LIPO is a package for derivative-free, global optimization. Is based on the dlib package and provides wrappers around its optimization routine."
  doc_url: https://github.com/jdb78/lipo
  dev_url: https://github.com/jdb78/lipo

extra:
  recipe-maintainers:
    - jdb78
